update

diff --git a/arcmail b/arcmail
--- a/arcmail
+++ b/arcmail
@@ -1,23 +1,24 @@
 #!/bin/bash
-# $Id: arcmail,v 1.33 2015/05/16 08:56:23 fulford Exp fulford $
+# $Id: arcmail,v 1.34 2015/05/16 16:20:51 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/arcmail,v $
-# $Revision: 1.33 $
+# $Revision: 1.34 $
 # Author C W Fulford.
 # Copyright 2015 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0709 229 5385
 ########################################################################
 cmd=`basename $0`
-ver=`echo "$Id: arcmail,v 1.33 2015/05/16 08:56:23 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
-syntax="$cmd [[-c <configfile>] [-d] [-l] [-m <max>] [-v] <email_address>]|[-V]"
+ver=`echo "$Id: arcmail,v 1.34 2015/05/16 16:20:51 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+syntax="$cmd [[-c <configfile>] [-d] [-i <company_id>] [-l] [-m <max>] [-v] <email_address>]|[-V]"
 while [ $# -gt 0 ] ;do
 	case $1 in 
 		-c) config=$2;shift 2;;
 		-d) set -x;debug=0;shift;;
+		-i) co=$2;shift 2;;
 		-l) log=:; shift;;
 		-m) clmax=$2;shift 2;;
 		-v) verbose=:;shift;;
-		-V) echo "$cmd $Revision: 1.33 $ $Date: 2015/05/16 08:56:23 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.34 $ $Date: 2015/05/16 16:20:51 $"|awk '{print $1,$3,$6}';exit;;  
 		 *@*) ma=$1;shift ;;
 	 	 *) echo "$syntax">&2; exit 1;;
 	esac
@@ -48,6 +49,10 @@ maildir=$basedir/$md/$mu/Maildir
 archf=$maildir/.Archive
 proto=${proto:-ssh}
 tmp=/tmp/$cmd$$
+
+[ -n "$co" ]||{
+	echo "$cmd: Warning - company id required for reporting" >&2
+}
 [ "$verbose" ] && echo "$cmd: maximum messages set to $max."
 if [ "$proto" == "ssh" ] ;then
 	c=`ssh $md "sudo bash -c \"cd $maildir/cur;ls -lt\""|
@@ -93,5 +98,5 @@ fi
 [ "$verbose" ]&&{
 	echo "$cmd: $etot messages remain in $mu's current INBOX at $md."
 }
-[ "$log" ]&& logger -p mail.notice -t $cmd "$mtot messages archived for $ma"
+[ "$log" ]&& logger -p mail.notice -t $cmd "$mtot messages archived for $ma at $co"
 rm $tmp
