update

diff --git a/arcmail b/arcmail
--- a/arcmail
+++ b/arcmail
@@ -1,7 +1,7 @@
 #!/bin/bash
-# $Id: arcmail,v 1.57 2015/06/18 18:27:25 fulford Exp fulford $
+# $Id: arcmail,v 1.58 2015/06/18 18:45:15 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/arcmail,v $
-# $Revision: 1.57 $
+# $Revision: 1.58 $
 # Author C W Fulford.
 # Copyright 2015 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
@@ -9,7 +9,7 @@
 ########################################################################
 cmd=`basename $0`
 chkmail=`dirname $0`/chkmail
-ver=`echo "$Id: arcmail,v 1.57 2015/06/18 18:27:25 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: arcmail,v 1.58 2015/06/18 18:45:15 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 syntax="$cmd [[-c <configfile>] [-d] [-i <company_id>] [-l] [-m <max>] [-v] <email_address>]|[-V]"
 while [ $# -gt 0 ] ;do
 	case $1 in 
@@ -23,7 +23,7 @@ while [ $# -gt 0 ] ;do
 		-l) log=:; shift;;
 		-m) clmax=$2;shift 2;;
 		-v) verbose=:;shift;;
-		-V) echo "$cmd $Revision: 1.57 $ $Date: 2015/06/18 18:27:25 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.58 $ $Date: 2015/06/18 18:45:15 $"|awk '{print $1,$3,$6}';exit;;  
 	     [^-]*@*) ma=$1;shift;;
 	         *)echo "$syntax">&2; exit 1;;
 	esac
@@ -63,8 +63,10 @@ tmp=/tmp/$cmd$$
 	echo "$cmd: max must be set to a positive integer" >&2
 	exit 1
 }
-[ -n "$co" ]||{
-	echo "$cmd: Warning - company id required for reporting" >&2
+[ "$log" ] && {
+	[ -n "$co" ]||{
+		echo "$cmd: Warning - company id required for reporting" >&2
+	}
 }
 [ "$verbose" ] && echo "$cmd: maximum messages set to $max."
 [ "$verbose" ]&& echo "$cmd: connecting to $md."
