update

diff --git a/arcmail b/arcmail
--- a/arcmail
+++ b/arcmail
@@ -1,7 +1,7 @@
 #!/bin/bash
-# $Id: arcmail,v 1.46 2015/05/26 07:04:42 fulford Exp $
+# $Id: arcmail,v 1.47 2015/05/26 08:03:57 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/arcmail,v $
-# $Revision: 1.46 $
+# $Revision: 1.47 $
 # Author C W Fulford.
 # Copyright 2015 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
@@ -9,7 +9,7 @@
 ########################################################################
 cmd=`basename $0`
 chkmail=`dirname $0`/chkmail
-ver=`echo "$Id: arcmail,v 1.46 2015/05/26 07:04:42 fulford Exp $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: arcmail,v 1.47 2015/05/26 08:03:57 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 syntax="$cmd [[-c <configfile>] [-d] [-i <company_id>] [-l] [-m <max>] [-v] <email_address>]|[-V]"
 while [ $# -gt 0 ] ;do
 	case $1 in 
@@ -19,12 +19,11 @@ while [ $# -gt 0 ] ;do
 		-l) log=:; shift;;
 		-m) clmax=$2;shift 2;;
 		-v) verbose=:;shift;;
-		-V) echo "$cmd $Revision: 1.46 $ $Date: 2015/05/26 07:04:42 $"|awk '{print $1,$3,$6}';exit;;  
-		 *@*) ma=$1;shift ;;
-	 	 *) echo "$syntax">&2; exit 1;;
+		-V) echo "$cmd $Revision: 1.47 $ $Date: 2015/05/26 08:03:57 $"|awk '{print $1,$3,$6}';exit;;  
+	     [^-]*@*) ma=$1;shift;;
+	         *)echo "$syntax">&2; exit 1;;
 	esac
 done
-
 
 [ "$ma" ] ||{ echo "$syntax" >&2;exit 1;}
 expr "$ma" : ".*@[^\.]*\.[^\.]*">/dev/null ||{
@@ -61,13 +60,22 @@ tmp=/tmp/$cmd$$
 [ "$verbose" ]&& echo "$cmd: connecting to $md."
 
 if [ "$proto" == "ssh" ] ;then
-	c=`ssh $md "sudo bash -c \"cd $maildir/cur;ls -lt\""|
+	ssh $md "sudo bash -c \"
+		[ -d $maildir/cur ] &&{
+	       		cd $maildir/cur 2>/dev/null &&
+			ls -lt \"
+	"|&
 		sed -e '/^total/d'|
-		tee $tmp|wc -l`
-	[ $c -le $max ] && {
-		echo "$cmd: $mu has $c current messages only" >&2
-		exit 1
-	}
+		tee $tmp |
+		c=`wc -l`
+		[ -z $c ] && {
+			echo "$cmd: $maildir/cur not found on $$md" >&2
+			exit 1
+		}
+		[ $c -le $max ] && {
+			echo "$cmd: $mu has $c current messages only" >&2
+			exit 1
+		}
 	f=`expr $max + 1`
 	[ "$verbose" ] &&{
        		echo "$cmd: moving `expr $c - $max` messages for $mu."
